/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecole221.prestation.kafka.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum CustomerStatut implements org.apache.avro.generic.GenericEnumSymbol<CustomerStatut> {
  CREATED, EXIST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CustomerStatut\",\"namespace\":\"com.ecole221.prestation.kafka.avro.model\",\"symbols\":[\"CREATED\",\"EXIST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
